// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dwell_fcw_streamer_dwell_fcw_streamer,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu49dr-ffvf1760-2-e,HLS_INPUT_CLOCK=4.069000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.746000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=68,HLS_SYN_LUT=237,HLS_VERSION=2024_1}" *)

module dwell_fcw_streamer (
        ap_clk,
        ap_rst_n,
        s_axis_cmd_TDATA,
        s_axis_cmd_TVALID,
        s_axis_cmd_TREADY,
        s_axis_cmd_TKEEP,
        s_axis_cmd_TSTRB,
        s_axis_cmd_TLAST,
        start_r,
        fcw_out,
        active_r,
        dwell_wait
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [63:0] s_axis_cmd_TDATA;
input   s_axis_cmd_TVALID;
output   s_axis_cmd_TREADY;
input  [7:0] s_axis_cmd_TKEEP;
input  [7:0] s_axis_cmd_TSTRB;
input  [0:0] s_axis_cmd_TLAST;
input  [0:0] start_r;
output  [31:0] fcw_out;
output  [0:0] active_r;
output  [0:0] dwell_wait;

 reg    ap_rst_n_inv;
reg   [31:0] current_fcw;
reg   [0:0] state;
reg   [31:0] dwell_remaining;
reg   [0:0] start_d;
reg   [0:0] current_word_was_last;
reg    s_axis_cmd_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] state_load_load_fu_122_p1;
wire   [0:0] and_ln67_fu_200_p2;
wire   [0:0] icmp_ln67_fu_194_p2;
reg    ap_predicate_op55_read_state1;
reg    ap_block_state1;
wire   [0:0] and_ln74_fu_224_p2;
wire   [0:0] start_edge_fu_154_p2;
wire   [31:0] add_ln72_fu_206_p2;
wire   [31:0] trunc_ln84_fu_272_p1;
wire   [0:0] icmp_ln41_fu_131_p2;
wire   [0:0] xor_ln43_fu_148_p2;
wire   [0:0] icmp_ln74_fu_218_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    regslice_both_s_axis_cmd_V_data_V_U_apdone_blk;
wire   [63:0] s_axis_cmd_TDATA_int_regslice;
wire    s_axis_cmd_TVALID_int_regslice;
reg    s_axis_cmd_TREADY_int_regslice;
wire    regslice_both_s_axis_cmd_V_data_V_U_ack_in;
wire    regslice_both_s_axis_cmd_V_keep_V_U_apdone_blk;
wire   [7:0] s_axis_cmd_TKEEP_int_regslice;
wire    regslice_both_s_axis_cmd_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_cmd_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_cmd_V_strb_V_U_apdone_blk;
wire   [7:0] s_axis_cmd_TSTRB_int_regslice;
wire    regslice_both_s_axis_cmd_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_cmd_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_cmd_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_cmd_TLAST_int_regslice;
wire    regslice_both_s_axis_cmd_V_last_V_U_vld_out;
wire    regslice_both_s_axis_cmd_V_last_V_U_ack_in;
reg    ap_condition_65;
reg    ap_condition_43;
reg    ap_condition_62;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 current_fcw = 32'd185685333;
#0 state = 1'd0;
#0 dwell_remaining = 32'd0;
#0 start_d = 1'd0;
#0 current_word_was_last = 1'd0;
#0 ap_CS_fsm = 1'd1;
end

dwell_fcw_streamer_regslice_both #(
    .DataWidth( 64 ))
regslice_both_s_axis_cmd_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_cmd_TDATA),
    .vld_in(s_axis_cmd_TVALID),
    .ack_in(regslice_both_s_axis_cmd_V_data_V_U_ack_in),
    .data_out(s_axis_cmd_TDATA_int_regslice),
    .vld_out(s_axis_cmd_TVALID_int_regslice),
    .ack_out(s_axis_cmd_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_cmd_V_data_V_U_apdone_blk)
);

dwell_fcw_streamer_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_cmd_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_cmd_TKEEP),
    .vld_in(s_axis_cmd_TVALID),
    .ack_in(regslice_both_s_axis_cmd_V_keep_V_U_ack_in),
    .data_out(s_axis_cmd_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_cmd_V_keep_V_U_vld_out),
    .ack_out(s_axis_cmd_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_cmd_V_keep_V_U_apdone_blk)
);

dwell_fcw_streamer_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_cmd_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_cmd_TSTRB),
    .vld_in(s_axis_cmd_TVALID),
    .ack_in(regslice_both_s_axis_cmd_V_strb_V_U_ack_in),
    .data_out(s_axis_cmd_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_cmd_V_strb_V_U_vld_out),
    .ack_out(s_axis_cmd_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_cmd_V_strb_V_U_apdone_blk)
);

dwell_fcw_streamer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_cmd_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_cmd_TLAST),
    .vld_in(s_axis_cmd_TVALID),
    .ack_in(regslice_both_s_axis_cmd_V_last_V_U_ack_in),
    .data_out(s_axis_cmd_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_cmd_V_last_V_U_vld_out),
    .ack_out(s_axis_cmd_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_cmd_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((1'd1 == and_ln67_fu_200_p2) & (state == 1'd1))) begin
            current_fcw <= 32'd185685333;
        end else if ((1'b1 == ap_condition_43)) begin
            current_fcw <= {{s_axis_cmd_TDATA_int_regslice[63:32]}};
        end else if ((1'b1 == ap_condition_65)) begin
            current_fcw <= 32'd185685333;
        end else if ((state_load_load_fu_122_p1 == 1'd0)) begin
            current_fcw <= 32'd185685333;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((1'd1 == and_ln67_fu_200_p2) & (state == 1'd1))) begin
            current_word_was_last <= 1'd0;
        end else if ((1'b1 == ap_condition_43)) begin
            current_word_was_last <= s_axis_cmd_TLAST_int_regslice;
        end else if ((1'b1 == ap_condition_65)) begin
            current_word_was_last <= 1'd0;
        end else if ((state_load_load_fu_122_p1 == 1'd0)) begin
            current_word_was_last <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((1'b1 == ap_condition_43)) begin
            dwell_remaining <= trunc_ln84_fu_272_p1;
        end else if ((1'b1 == ap_condition_62)) begin
            dwell_remaining <= add_ln72_fu_206_p2;
        end else if ((state_load_load_fu_122_p1 == 1'd0)) begin
            dwell_remaining <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state1) & (1'd1 == and_ln67_fu_200_p2) & (state == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state1) & (icmp_ln67_fu_194_p2 == 1'd0) & (1'd1 == and_ln74_fu_224_p2) & (state == 1'd1) & (1'd0 == and_ln67_fu_200_p2) & (1'b1 == ap_CS_fsm_state1)))) begin
        state <= 1'd0;
    end else if (((start_edge_fu_154_p2 == 1'd1) & (1'b0 == ap_block_state1) & (state_load_load_fu_122_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        state <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        start_d <= start_r;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_194_p2 == 1'd1) & (state == 1'd1) & (1'd0 == and_ln67_fu_200_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_cmd_TDATA_blk_n = s_axis_cmd_TVALID_int_regslice;
    end else begin
        s_axis_cmd_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (ap_predicate_op55_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_cmd_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_cmd_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign active_r = state;

assign add_ln72_fu_206_p2 = ($signed(dwell_remaining) + $signed(32'd4294967295));

assign and_ln67_fu_200_p2 = (icmp_ln67_fu_194_p2 & current_word_was_last);

assign and_ln74_fu_224_p2 = (icmp_ln74_fu_218_p2 & current_word_was_last);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_predicate_op55_read_state1 == 1'b1) & (s_axis_cmd_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_43 = ((icmp_ln67_fu_194_p2 == 1'd1) & (state == 1'd1) & (1'd0 == and_ln67_fu_200_p2));
end

always @ (*) begin
    ap_condition_62 = ((icmp_ln67_fu_194_p2 == 1'd0) & (state == 1'd1) & (1'd0 == and_ln67_fu_200_p2));
end

always @ (*) begin
    ap_condition_65 = ((icmp_ln67_fu_194_p2 == 1'd0) & (1'd1 == and_ln74_fu_224_p2) & (state == 1'd1) & (1'd0 == and_ln67_fu_200_p2));
end

always @ (*) begin
    ap_predicate_op55_read_state1 = ((icmp_ln67_fu_194_p2 == 1'd1) & (state == 1'd1) & (1'd0 == and_ln67_fu_200_p2));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dwell_wait = (state & icmp_ln41_fu_131_p2);

assign fcw_out = current_fcw;

assign icmp_ln41_fu_131_p2 = ((dwell_remaining != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_194_p2 = ((dwell_remaining == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_218_p2 = ((add_ln72_fu_206_p2 == 32'd0) ? 1'b1 : 1'b0);

assign s_axis_cmd_TREADY = regslice_both_s_axis_cmd_V_data_V_U_ack_in;

assign start_edge_fu_154_p2 = (xor_ln43_fu_148_p2 & start_r);

assign state_load_load_fu_122_p1 = state;

assign trunc_ln84_fu_272_p1 = s_axis_cmd_TDATA_int_regslice[31:0];

assign xor_ln43_fu_148_p2 = (start_d ^ 1'd1);


reg find_kernel_block = 0;
// synthesis translate_off
`include "dwell_fcw_streamer_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //dwell_fcw_streamer

