// Generated by scripts/generate_laser_pll_tables.py; signed Q1.17.
function automatic signed [17:0] fir_coefficient(input integer tap);
    case (tap)
        0: fir_coefficient = -18'sd5;
        1: fir_coefficient = -18'sd37;
        2: fir_coefficient = -18'sd116;
        3: fir_coefficient = -18'sd255;
        4: fir_coefficient = -18'sd431;
        5: fir_coefficient = -18'sd575;
        6: fir_coefficient = -18'sd557;
        7: fir_coefficient = -18'sd204;
        8: fir_coefficient = 18'sd661;
        9: fir_coefficient = 18'sd2166;
        10: fir_coefficient = 18'sd4329;
        11: fir_coefficient = 18'sd7018;
        12: fir_coefficient = 18'sd9943;
        13: fir_coefficient = 18'sd12701;
        14: fir_coefficient = 18'sd14857;
        15: fir_coefficient = 18'sd16041;
        16: fir_coefficient = 18'sd16041;
        17: fir_coefficient = 18'sd14857;
        18: fir_coefficient = 18'sd12701;
        19: fir_coefficient = 18'sd9943;
        20: fir_coefficient = 18'sd7018;
        21: fir_coefficient = 18'sd4329;
        22: fir_coefficient = 18'sd2166;
        23: fir_coefficient = 18'sd661;
        24: fir_coefficient = -18'sd204;
        25: fir_coefficient = -18'sd557;
        26: fir_coefficient = -18'sd575;
        27: fir_coefficient = -18'sd431;
        28: fir_coefficient = -18'sd255;
        29: fir_coefficient = -18'sd116;
        30: fir_coefficient = -18'sd37;
        31: fir_coefficient = -18'sd5;
        default: fir_coefficient = 0;
    endcase
endfunction
