"""Generate fixed DDS/FIR constants for the 1.96608 GS/s laser PLL."""
from pathlib import Path
import numpy as np
from scipy.signal import firwin

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "TransportPhaseLockFF.srcs/sources_1/new"

# Midpoint sampling makes quadrant reflection exact, without a special endpoint.
angle_rad = (np.arange(16384) + 0.5) * np.pi / 32768
sine = np.rint(131071 * np.sin(angle_rad)).astype(int)
(OUT / "laser_pll_sine.mem").write_text("".join(f"{x:05x}\n" for x in sine))

# Wide enough for +/-100 MHz acquisition; rejects the 266..466 MHz image
# of a 700..900 MHz real input mixed against an 800 MHz reference.
h = firwin(32, 120e6, fs=1.96608e9, window=("kaiser", 7.0))
coeff = np.rint(h * 131072).astype(int)
coeff[15:17] += (131072 - coeff.sum()) // 2
assert coeff.sum() == 131072
(OUT / "laser_pll_fir_coeffs.vh").write_text(
    "// Generated by scripts/generate_laser_pll_tables.py; signed Q1.17.\n"
    + "function automatic signed [17:0] fir_coefficient(input integer tap);\n"
    + "    case (tap)\n"
    + "".join(f"        {i}: fir_coefficient = {'-' if c < 0 else ''}18'sd{abs(c)};\n"
              for i, c in enumerate(coeff))
    + "        default: fir_coefficient = 0;\n    endcase\nendfunction\n")
