-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dwell_fcw_streamer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_cmd_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axis_cmd_TVALID : IN STD_LOGIC;
    s_axis_cmd_TREADY : OUT STD_LOGIC;
    s_axis_cmd_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    s_axis_cmd_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    s_axis_cmd_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    start_r : IN STD_LOGIC_VECTOR (0 downto 0);
    fcw_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    active_r : OUT STD_LOGIC_VECTOR (0 downto 0);
    dwell_wait : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of dwell_fcw_streamer is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dwell_fcw_streamer_dwell_fcw_streamer,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu49dr-ffvf1760-2-e,HLS_INPUT_CLOCK=4.069000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.746000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=68,HLS_SYN_LUT=237,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B115555_1 : STD_LOGIC_VECTOR (31 downto 0) := "00001011000100010101010101010101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_B115555_2 : STD_LOGIC_VECTOR (31 downto 0) := "00001011000100010101010101010101";
    constant ap_const_lv32_B115555_3 : STD_LOGIC_VECTOR (31 downto 0) := "00001011000100010101010101010101";
    constant ap_const_lv1_0_4 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_0_5 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_0_6 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal current_fcw : STD_LOGIC_VECTOR (31 downto 0) := "00001011000100010101010101010101";
    signal state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal dwell_remaining : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal start_d : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal current_word_was_last : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal s_axis_cmd_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal state_load_load_fu_122_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln67_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op55_read_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal and_ln74_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal start_edge_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln72_fu_206_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln84_fu_272_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln41_fu_131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_cmd_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal s_axis_cmd_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_cmd_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_cmd_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_s_axis_cmd_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_cmd_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_s_axis_cmd_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_cmd_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_cmd_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_cmd_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_condition_65 : BOOLEAN;
    signal ap_condition_43 : BOOLEAN;
    signal ap_condition_62 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component dwell_fcw_streamer_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_s_axis_cmd_V_data_V_U : component dwell_fcw_streamer_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_cmd_TDATA,
        vld_in => s_axis_cmd_TVALID,
        ack_in => regslice_both_s_axis_cmd_V_data_V_U_ack_in,
        data_out => s_axis_cmd_TDATA_int_regslice,
        vld_out => s_axis_cmd_TVALID_int_regslice,
        ack_out => s_axis_cmd_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_cmd_V_data_V_U_apdone_blk);

    regslice_both_s_axis_cmd_V_keep_V_U : component dwell_fcw_streamer_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_cmd_TKEEP,
        vld_in => s_axis_cmd_TVALID,
        ack_in => regslice_both_s_axis_cmd_V_keep_V_U_ack_in,
        data_out => s_axis_cmd_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_cmd_V_keep_V_U_vld_out,
        ack_out => s_axis_cmd_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_cmd_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_cmd_V_strb_V_U : component dwell_fcw_streamer_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_cmd_TSTRB,
        vld_in => s_axis_cmd_TVALID,
        ack_in => regslice_both_s_axis_cmd_V_strb_V_U_ack_in,
        data_out => s_axis_cmd_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_cmd_V_strb_V_U_vld_out,
        ack_out => s_axis_cmd_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_cmd_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_cmd_V_last_V_U : component dwell_fcw_streamer_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_cmd_TLAST,
        vld_in => s_axis_cmd_TVALID,
        ack_in => regslice_both_s_axis_cmd_V_last_V_U_ack_in,
        data_out => s_axis_cmd_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_cmd_V_last_V_U_vld_out,
        ack_out => s_axis_cmd_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_cmd_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    current_fcw_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if (((ap_const_lv1_1 = and_ln67_fu_200_p2) and (state = ap_const_lv1_1))) then 
                    current_fcw <= ap_const_lv32_B115555_3;
                elsif ((ap_const_boolean_1 = ap_condition_43)) then 
                    current_fcw <= s_axis_cmd_TDATA_int_regslice(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    current_fcw <= ap_const_lv32_B115555_2;
                elsif ((state_load_load_fu_122_p1 = ap_const_lv1_0)) then 
                    current_fcw <= ap_const_lv32_B115555_1;
                end if;
            end if; 
        end if;
    end process;

    current_word_was_last_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if (((ap_const_lv1_1 = and_ln67_fu_200_p2) and (state = ap_const_lv1_1))) then 
                    current_word_was_last <= ap_const_lv1_0_6;
                elsif ((ap_const_boolean_1 = ap_condition_43)) then 
                    current_word_was_last <= s_axis_cmd_TLAST_int_regslice;
                elsif ((ap_const_boolean_1 = ap_condition_65)) then 
                    current_word_was_last <= ap_const_lv1_0_5;
                elsif ((state_load_load_fu_122_p1 = ap_const_lv1_0)) then 
                    current_word_was_last <= ap_const_lv1_0_4;
                end if;
            end if; 
        end if;
    end process;

    dwell_remaining_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((ap_const_boolean_1 = ap_condition_43)) then 
                    dwell_remaining <= trunc_ln84_fu_272_p1;
                elsif ((ap_const_boolean_1 = ap_condition_62)) then 
                    dwell_remaining <= add_ln72_fu_206_p2;
                elsif ((state_load_load_fu_122_p1 = ap_const_lv1_0)) then 
                    dwell_remaining <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_state1) and (ap_const_lv1_1 = and_ln67_fu_200_p2) and (state = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_state1) and (icmp_ln67_fu_194_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln74_fu_224_p2) and (state = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln67_fu_200_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                state <= ap_const_lv1_0;
            elsif (((start_edge_fu_154_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1) and (state_load_load_fu_122_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                state <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                start_d <= start_r;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    active_r <= state;
    add_ln72_fu_206_p2 <= std_logic_vector(unsigned(dwell_remaining) + unsigned(ap_const_lv32_FFFFFFFF));
    and_ln67_fu_200_p2 <= (icmp_ln67_fu_194_p2 and current_word_was_last);
    and_ln74_fu_224_p2 <= (icmp_ln74_fu_218_p2 and current_word_was_last);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_predicate_op55_read_state1, s_axis_cmd_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((ap_predicate_op55_read_state1 = ap_const_boolean_1) and (s_axis_cmd_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_43_assign_proc : process(state, and_ln67_fu_200_p2, icmp_ln67_fu_194_p2)
    begin
                ap_condition_43 <= ((icmp_ln67_fu_194_p2 = ap_const_lv1_1) and (state = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln67_fu_200_p2));
    end process;


    ap_condition_62_assign_proc : process(state, and_ln67_fu_200_p2, icmp_ln67_fu_194_p2)
    begin
                ap_condition_62 <= ((icmp_ln67_fu_194_p2 = ap_const_lv1_0) and (state = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln67_fu_200_p2));
    end process;


    ap_condition_65_assign_proc : process(state, and_ln67_fu_200_p2, icmp_ln67_fu_194_p2, and_ln74_fu_224_p2)
    begin
                ap_condition_65 <= ((icmp_ln67_fu_194_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln74_fu_224_p2) and (state = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln67_fu_200_p2));
    end process;


    ap_predicate_op55_read_state1_assign_proc : process(state, and_ln67_fu_200_p2, icmp_ln67_fu_194_p2)
    begin
                ap_predicate_op55_read_state1 <= ((icmp_ln67_fu_194_p2 = ap_const_lv1_1) and (state = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln67_fu_200_p2));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    dwell_wait <= (state and icmp_ln41_fu_131_p2);
    fcw_out <= current_fcw;
    icmp_ln41_fu_131_p2 <= "0" when (dwell_remaining = ap_const_lv32_0) else "1";
    icmp_ln67_fu_194_p2 <= "1" when (dwell_remaining = ap_const_lv32_0) else "0";
    icmp_ln74_fu_218_p2 <= "1" when (add_ln72_fu_206_p2 = ap_const_lv32_0) else "0";

    s_axis_cmd_TDATA_blk_n_assign_proc : process(state, ap_CS_fsm_state1, and_ln67_fu_200_p2, icmp_ln67_fu_194_p2, s_axis_cmd_TVALID_int_regslice)
    begin
        if (((icmp_ln67_fu_194_p2 = ap_const_lv1_1) and (state = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln67_fu_200_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_cmd_TDATA_blk_n <= s_axis_cmd_TVALID_int_regslice;
        else 
            s_axis_cmd_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_cmd_TREADY <= regslice_both_s_axis_cmd_V_data_V_U_ack_in;

    s_axis_cmd_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_predicate_op55_read_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_predicate_op55_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_cmd_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_cmd_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    start_edge_fu_154_p2 <= (xor_ln43_fu_148_p2 and start_r);
    state_load_load_fu_122_p1 <= state;
    trunc_ln84_fu_272_p1 <= s_axis_cmd_TDATA_int_regslice(32 - 1 downto 0);
    xor_ln43_fu_148_p2 <= (start_d xor ap_const_lv1_1);
end behav;
